package cn.liupengstudy.family_finance_system.pojo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "消费明目关系实体")
public class ConsumerRelationship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ConsumerRelationship.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "自增ID")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ConsumerRelationship.fatherID
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "父级ID")
    private Integer fatherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ConsumerRelationship.sonID
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "子级ID")
    private Integer sonid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ConsumerRelationship.id
     *
     * @return the value of ConsumerRelationship.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ConsumerRelationship.id
     *
     * @param id the value for ConsumerRelationship.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ConsumerRelationship.fatherID
     *
     * @return the value of ConsumerRelationship.fatherID
     *
     * @mbggenerated
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ConsumerRelationship.fatherID
     *
     * @param fatherid the value for ConsumerRelationship.fatherID
     *
     * @mbggenerated
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ConsumerRelationship.sonID
     *
     * @return the value of ConsumerRelationship.sonID
     *
     * @mbggenerated
     */
    public Integer getSonid() {
        return sonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ConsumerRelationship.sonID
     *
     * @param sonid the value for ConsumerRelationship.sonID
     *
     * @mbggenerated
     */
    public void setSonid(Integer sonid) {
        this.sonid = sonid;
    }

    @Override
    public String toString() {
        return "ConsumerRelationship{" +
                "id=" + id +
                ", fatherid=" + fatherid +
                ", sonid=" + sonid +
                '}';
    }
}