package cn.liupengstudy.family_finance_system.pojo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiOperation;

import java.util.Date;

@ApiModel(value = "流水账实体")
public class RunningAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.necessaryConsume
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "是否必要消费")
    private Integer necessaryconsume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.itemsNumber
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "消费明目编号")
    private Integer itemsnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "消费金额")
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.datetime
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "消费日期时间")
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.remarks
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注")
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.city
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "城市")
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.Latitude
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "经度")
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RunningAccount.Llongitude
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "纬度")
    private Double llongitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.id
     *
     * @return the value of RunningAccount.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.id
     *
     * @param id the value for RunningAccount.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.necessaryConsume
     *
     * @return the value of RunningAccount.necessaryConsume
     *
     * @mbggenerated
     */
    public Integer getNecessaryconsume() {
        return necessaryconsume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.necessaryConsume
     *
     * @param necessaryconsume the value for RunningAccount.necessaryConsume
     *
     * @mbggenerated
     */
    public void setNecessaryconsume(Integer necessaryconsume) {
        this.necessaryconsume = necessaryconsume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.itemsNumber
     *
     * @return the value of RunningAccount.itemsNumber
     *
     * @mbggenerated
     */
    public Integer getItemsnumber() {
        return itemsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.itemsNumber
     *
     * @param itemsnumber the value for RunningAccount.itemsNumber
     *
     * @mbggenerated
     */
    public void setItemsnumber(Integer itemsnumber) {
        this.itemsnumber = itemsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.amount
     *
     * @return the value of RunningAccount.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.amount
     *
     * @param amount the value for RunningAccount.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.datetime
     *
     * @return the value of RunningAccount.datetime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.datetime
     *
     * @param datetime the value for RunningAccount.datetime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.remarks
     *
     * @return the value of RunningAccount.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.remarks
     *
     * @param remarks the value for RunningAccount.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.city
     *
     * @return the value of RunningAccount.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.city
     *
     * @param city the value for RunningAccount.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.Latitude
     *
     * @return the value of RunningAccount.Latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.Latitude
     *
     * @param latitude the value for RunningAccount.Latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RunningAccount.Llongitude
     *
     * @return the value of RunningAccount.Llongitude
     *
     * @mbggenerated
     */
    public Double getLlongitude() {
        return llongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RunningAccount.Llongitude
     *
     * @param llongitude the value for RunningAccount.Llongitude
     *
     * @mbggenerated
     */
    public void setLlongitude(Double llongitude) {
        this.llongitude = llongitude;
    }
}