package cn.liupengstudy.family_finance_system.service;

import cn.liupengstudy.family_finance_system.pojo.ConsumerRelationship;

/**
 * @文件名 cn.liupengstudy.family_finance_system.service
 * @描述
 * @创建人 liupeng
 * @作者联系方式 LIUPENG.0@outlook.com
 * @创建时间 2019/11/17 - 5:52 上午
 * @修改人和其它信息
 */
public interface IConsumerRelationship {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int insert(ConsumerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int insertSelective(ConsumerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    ConsumerRelationship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConsumerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConsumerRelationship record);

}
