package cn.liupengstudy.family_finance_system.service;

import cn.liupengstudy.family_finance_system.pojo.FatherOverheadItems;

/**
 * @文件名 cn.liupengstudy.family_finance_system.service
 * @描述
 * @创建人 liupeng
 * @作者联系方式 LIUPENG.0@outlook.com
 * @创建时间 2019/11/12 - 2:49 下午
 * @修改人和其它信息
 */
public interface IFatherOverheadItems {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int insert(FatherOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int insertSelective(FatherOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    FatherOverheadItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FatherOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FatherOverheadItems record);
}
