package cn.liupengstudy.family_finance_system.service;

import cn.liupengstudy.family_finance_system.pojo.RunningAccount;

import java.util.Date;
import java.util.List;

/**
 * @文件名 cn.liupengstudy.family_finance_system.service
 * @描述
 * @创建人 liupeng
 * @作者联系方式 LIUPENG.0@outlook.com
 * @创建时间 2019/11/16 - 8:38 上午
 * @修改人和其它信息
 */
public interface IRunningAccount {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RunningAccount
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RunningAccount
     *
     * @mbggenerated
     */
    int insert(RunningAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RunningAccount
     *
     * @mbggenerated
     */
    int insertSelective(RunningAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RunningAccount
     *
     * @mbggenerated
     */
    RunningAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RunningAccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RunningAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RunningAccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RunningAccount record);

    /**
     * @描述  通过Date获取List<RunningAccount>
     * @参数  Date date
     * @返回值  List<RunningAccount>
     * @创建人  liupeng
     * @作者联系方式 LIUPENG.0@outlook.com
     * @创建时间  2019/11/19 - 8:28 上午
     * @修改人和其它信息
     */
    List<RunningAccount> getRunningAccountByDate();
}

