package cn.liupengstudy.family_finance_system.service;

import cn.liupengstudy.family_finance_system.pojo.SonOverheadItems;
import cn.liupengstudy.family_finance_system.pojo.StringType;

/**
 * @文件名 cn.liupengstudy.family_finance_system.service
 * @描述
 * @创建人 liupeng
 * @作者联系方式 LIUPENG.0@outlook.com
 * @创建时间 2019/11/15 - 7:35 上午
 * @修改人和其它信息
 */
public interface ISonOverheadItems {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SonOverheadItems
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SonOverheadItems
     *
     * @mbggenerated
     */
    int insert(SonOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SonOverheadItems
     *
     * @mbggenerated
     */
    int insertSelective(SonOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SonOverheadItems
     *
     * @mbggenerated
     */
    SonOverheadItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SonOverheadItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SonOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SonOverheadItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SonOverheadItems record);

    /**
     * @描述  通过消费明目获取消费明目的ID
     * @参数  [name]
     * @返回值  int
     * @创建人  liupeng
     * @作者联系方式 LIUPENG.0@outlook.com
     * @创建时间  2019/11/20 - 8:40 下午
     * @修改人和其它信息
     */
    StringType getIDByName(String name);
}
