package cn.liupengstudy.family_finance_system.mapper;

import cn.liupengstudy.family_finance_system.pojo.ConsumerRelationship;

public interface ConsumerRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int insert(ConsumerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int insertSelective(ConsumerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    ConsumerRelationship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConsumerRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ConsumerRelationship
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConsumerRelationship record);
}