package cn.liupengstudy.family_finance_system.mapper;

import cn.liupengstudy.family_finance_system.pojo.FatherOverheadItems;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FatherOverheadItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int insert(FatherOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int insertSelective(FatherOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    FatherOverheadItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FatherOverheadItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FatherOverheadItems
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FatherOverheadItems record);
}